###
GET http://localhost:8080/api/person/

###
GET http://localhost:8080/api/knowledge/

###
GET http://localhost:8080/api/expectation/

###
GET http://localhost:8080/api/answer/

###
GET http://localhost:8080/api/question/
