###
GET http://localhost:8080/api/person/
###
POST http://localhost:8080/api/person/
Content-Type: application/json

{
  "uuid": "1100000-0000-0000-0000-000000000000"
}

###
POST http://localhost:8080/api/person/26/knowledge
Content-Type: application/json

{
  "name": "Manager"
}

###
GET http://localhost:8080/api/knowledge/

###
POST http://localhost:8080/api/knowledge/
Content-Type: application/json

{
    "name": "new some testing"
}
###
POST http://localhost:8080/api/knowledge/46
Content-Type: application/json

{
    "name": "VIM mode"
}
###
GET http://localhost:8080/api/expectation/

###
GET http://localhost:8080/api/answer/

###
GET http://localhost:8080/api/question/
