###
GET http://localhost:8080/api/person/

###
curl -H "Content-Type: application/json" -d '{"uuid": "1100000-0000-0000-0000-000000000000", "login":"miroque"}' http://localhost:8080/api/person/


###
POST http://localhost:8080/api/person/
Content-Type: application/json

{
  "login": "fooz"
}

###
PUT http://localhost:8080/api/person/2e35fa07-34a6-44d5-8caa-a6c5fa0088d9/
Content-Type: application/json

{
  "login": "foo-1-z",
  "level": 200,
  "recalculated": "2020-01-01T16:01:01"
}

###
POST http://localhost:8080/api/person/26/knowledge
Content-Type: application/json

{
  "name": "Manager"
}

###
GET http://localhost:8080/api/knowledge/

###
POST http://localhost:8080/api/knowledge/
Content-Type: application/json

{
    "name": "new some testing"
}
###
POST http://localhost:8080/api/knowledge/46
Content-Type: application/json

{
    "name": "VIM mode"
}
###
GET http://localhost:8080/api/expectation/

###
GET http://localhost:8080/api/answer/

###
GET http://localhost:8080/api/question/
